extends: existence
message: "Abbreviation of "for example". Must be followed by a comma and be enclosed in parentheses like "(e.g., Example)"."
level: warning
code: false
ignorecase: true
tokens:
    - e.g.
