extends: existence
message: "Abbreviation of "for example". Must be followed by a comma and be enclosed in parentheses like "('%s', Example)"."
level: warning
code: false
ignorecase: true
tokens: 
  - tomato
