remote_theme: pmarsceill/just-the-docs

logo: "/assets/logo-placeholder.png"

plugins:
  - jekyll-seo-tag

# Jekyll SEO Configuration
title: LM
description: Learn, explore and troubleshoot with Product's Support Center.
canonical_url: https://www.example.com/support
locale: en_US
seo:
  type: article
  name: Product Support Center
twitter:
  card: summary_large_image
