name: Link Checker

on:
  pull_request:
    types: 
      - labeled

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'link check')
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
