name: 'Markdown Formatting Check 2'
on:
  pull_request:
    types: 
      - labeled
jobs:
  Markdown-lint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'markdownlint')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: **/converted-posts/*.md
      - name: Annotate markdown errors
        uses: xt0rted/markdownlint-problem-matcher@v1
        run: markdownlint **/*.md --ignore node_modules
