name: 'Markdown Formatting Check 2'
on:
  pull_request:
    types: 
      - labeled
jobs:
  Lint-Markdown-Two:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'markdownlint')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - name: Run markdownlint problem matcher
        run: markdownlint ./*.md --ignore node_modules
