name: PR Link Checker

on: 
  pull_request:
    types: 
      - labeled
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'link check')
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.3.2
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
