name: Style Guide Check
on: 
  pull_request:
    types: [labeled, push]

jobs:
  Vale-lint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'style guide check')
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Vale Linter
        uses: errata-ai/vale-action@v1.4.3
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
